### ISSUE TITLE
用 tsx 作为模版文件产生错误

### ISSUE THREAD

**Issue by zaaack** [qiu8310/minapp#14]
RT，我在本地用 tsx 作为模版文件编译成 wxml, 但是会导致编译失败，提示无法 resolve tsx 文件，需要一个合适的 loader。 tsx 文件并没有被其他文件引入，预期是能忽略掉 tsx 文件

ps: 把 counter.tsx 改成 counter-wxml.tsx 就好了

```ts
WARNING in ./src/app.scss.d.ts
[at-loader] TypeScript declaration files should never be required
Error: [at-loader] TypeScript declaration files should never be required
    at compiler (/Users/z/.config/yarn/global/node_modules/awesome-typescript-loader/src/index.ts:54:28)
    at Object.loader (/Users/z/.config/yarn/global/node_modules/awesome-typescript-loader/src/index.ts:16:18)
 @ ./src/app.cjson 16:0-68

WARNING in ./src/components/counter/counter.scss.d.ts
[at-loader] TypeScript declaration files should never be required
Error: [at-loader] TypeScript declaration files should never be required
    at compiler (/Users/z/.config/yarn/global/node_modules/awesome-typescript-loader/src/index.ts:54:28)
    at Object.loader (/Users/z/.config/yarn/global/node_modules/awesome-typescript-loader/src/index.ts:16:18)
 @ ./src/pages/index/index.cjson 3:0-91 11:0-91
 @ ./src/app.cjson

ERROR in ./src/components/counter/counter.tsx
Module parse failed: Unexpected token (3:37)
You may need an appropriate loader to handle this file type.
| import * as css from './counter.scss'
|
| export default function Counter(props: any) {
|   return (
|     <view class={css.counter}>{props.start}</view>
 @ ./src/pages/index/index.cjson 6:0-85 14:0-85
 @ ./src/app.cjson
```

**Comment by qiu8310** [comment]
嗯，loader 没加 tsx 语言

**Comment by zaaack** [comment]
@qiu8310 我希望tsx能不编译，问题是没加loader也会走webpack，只是名字和组件名相同

**Comment by qiu8310** [comment]
一直没看到你下面的回复，是的，默认我会遍历这个目录下的同名的文件，如果你不希望走 webpack，你就把文件的名称换成一个和 文件夹名称不同的就行了

主要是目录下可能有 js/ts/json/cjson/scss/less/wxss/css 等等，我偷懒，只要是同名的我就加载

**Comment by zaaack** [comment]
目前我就是这样解决的。。
