### ISSUE TITLE
Can't resolve 'pages/Index/Index'

### ISSUE THREAD

**Issue by Allenice** [qiu8310/minapp#70]
我在 mac 环境下运行没有问题，但是在 linux 下却报错了，提示 Can't resolve 'pages/Index/Index' in  ./src/app.cjson

**Comment by Allenice** [comment]
ERROR in ./src/app.cjson
Can't resolve 'pages/Index/Index' in '/home/allenice/project/test/src'
Error: Can't resolve 'pages/Index/Index' in '/home/allenice/project/test/src'
    at onError (/home/allenice/project/test/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:61:15)
    at loggingCallbackWrapper (/home/allenice/project/test/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/home/allenice/project/test/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/home/allenice/project/test/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/home/allenice/project/test/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/allenice/project/test/node_modules/tapable/lib/Tapable.js:252:11)
    at /home/allenice/project/test/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/home/allenice/project/test/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/home/allenice/project/test/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/home/allenice/project/test/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:146:3)

ERROR in ./src/app.cjson
Module build failed: Error: Final loader didn't return a Buffer or String
    at runLoaders (/home/allenice/project/test/node_modules/webpack/lib/NormalModule.js:204:46)
    at /home/allenice/project/test/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/home/allenice/project/test/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at iterateNormalLoaders (/home/allenice/project/test/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /home/allenice/project/test/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at /home/allenice/project/test/node_modules/loader-runner/lib/LoaderRunner.js:127:6
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by qiu8310** [comment]
我在 Ubuntu 上试了，是没问题的，你查看下文件大小写是不是统一的，我看到你 app.cjson 中用了大写的 Index，那么 src/pages/Index 文件夹下的所有文件开头也要是大写的 `I`

![image](https://user-images.githubusercontent.com/1094697/40399628-fa8d5f3c-5e70-11e8-89b6-aade96603ed9.png)

**Comment by Allenice** [comment]
![image](https://user-images.githubusercontent.com/2650994/40401389-c3739c34-5e78-11e8-88cd-c765cd1c5287.png)
大小写是统一的，然后我的 minapp 版本是 1.0.15 的，我看你后面有个提交是处理文件名大小写的，会不会是这个问题？

**Comment by qiu8310** [comment]
我映象中没有出现过这个问题

建义你升级 minapp/cli 试试，2.0 改动不大的，主要就修改下 package.json 文件 https://qiu8310.github.io/minapp/docs/doc-update-v1-to-v2.html
